version: "3.9"

services:
  api:
    build: .
    container_name: fraud_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    depends_on:
      - mlflow
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: mlflow_ui
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns

